[package]
name = "bagelwithlox"
description = "rust version of the Crafting Interpreters lox language"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
prev-iter = "0.2.0"
rustyline = "15.0.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
